# Setup
title:               Burnt Thyme Labs
tagline:             'Design'
description:         'Burnt Thyme Labs is a location for all types of design experiments'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Tehan Dassanayaka
  url:               jtehand.github.io
  email:             jtehand@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
